version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2
  ignore:
    - dependency-name: "github.com/twbs/bootstrap"
    - dependency-name: "github.com/FortAwesome/Font-Awesome"
