version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "github.com/twbs/bootstrap"
      - dependency-name: "github.com/FortAwesome/Font-Awesome"